# Task 2

In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('fruit_data_with_colors _1_.csv')

In [3]:
df.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score
0            1      apple  granny_smith  192.0    8.4     7.3         0.55
1            1      apple  granny_smith  180.0    8.0     6.8         0.59
2            1      apple  granny_smith  176.0    7.4     7.2         0.60
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79

In [4]:
df = df.drop(['fruit_name', 'fruit_subtype'], axis=1)

In [5]:
df.head()

fruit_label   mass  width  height  color_score
0            1  192.0    8.4     7.3         0.55
1            1  180.0    8.0     6.8         0.59
2            1  176.0    7.4     7.2         0.60
3            2   86.0    6.2     4.7         0.80
4            2   84.0    6.0     4.6         0.79

In [6]:
x = df["mass"].mean()
y =  df["height"].mean()

df["mass"].fillna(x, inplace = True)
df["height"].fillna(y, inplace = True)
df.head()

fruit_label   mass  width  height  color_score
0            1  192.0    8.4     7.3         0.55
1            1  180.0    8.0     6.8         0.59
2            1  176.0    7.4     7.2         0.60
3            2   86.0    6.2     4.7         0.80
4            2   84.0    6.0     4.6         0.79

In [34]:
# Split the data into training and testing sets
X = df[[ 'mass','width','height','color_score']]
y = df['fruit_label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.16, random_state=0)

In [40]:
X_test

mass  width    height  color_score
26  356.000000    9.2  9.200000         0.75
35  142.000000    7.6  7.800000         0.75
59  118.000000    6.1  8.100000         0.70
28  204.000000    7.5  9.200000         0.77
11  172.000000    7.1  7.600000         0.92
2   176.000000    7.4  7.200000         0.60
34  190.000000    7.5  8.100000         0.74
58  152.000000    6.5  8.500000         0.72
40  154.000000    7.3  7.500000         0.76
22  762.039216    7.3  7.711765         0.72

In [102]:
knn = KNeighborsClassifier(n_neighbors=1)

In [103]:
# Train the model using the fit method
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [104]:
y_pred= knn.predict(X_test) # predict y labels on testing values for x
y_pred

array([3, 3, 4, 4, 1, 1, 1, 1, 3, 4], dtype=int64)

In [105]:
accuracy = accuracy_score(y_test, y_pred) #by calculating accuracy at k = 1 gives the good results
print("Accuracy:", accuracy)

Accuracy: 0.7


In [106]:
knn = KNeighborsClassifier(n_neighbors = 35) #predict x value of on k = 35
knn.fit(X_train, y_train)
y_pred= knn.predict(X_test) 
y_pred

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [107]:
accuracy = accuracy_score(y_test, y_pred) #calculating accuracy is at k = 35 is not good then accuracy at k = 1
print("Accuracy:", accuracy)

Accuracy: 0.3


In [114]:
knn = KNeighborsClassifier(n_neighbors = 15) #predict x value of on k = 35
knn.fit(X_train, y_train)
y_pred= knn.predict(X_test) 
y_pred

array([1, 3, 4, 1, 3, 1, 1, 3, 3, 4], dtype=int64)

In [115]:
accuracy = accuracy_score(y_test, y_pred) #calculating accuracy is at k = 35 is also not good then accuracy at k = 1
print("Accuracy:", accuracy)

#conclusion by increasing the value of k form 1 the accuracy will be decreased

Accuracy: 0.5


# Task 1

In [42]:
import numpy as np # only use this to make a function

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        y_pred = []

        for x in X:
            distances = []
            for i in range(len(self.X_train)):
                distance = np.sqrt(np.sum(np.square(x - self.X_train[i])))
                distances.append((distance, self.y_train[i]))
            distances.sort()
            k_nearest = distances[:self.k]
            k_nearest_labels = [label for (_, label) in k_nearest]
            y_pred.append(max(set(k_nearest_labels), key=k_nearest_labels.count))

        return y_pred


In [19]:
# import math
# keys = ['Math', 'CS', 'Result']
# values = [
#             [4, 6, 7 ,5 ,8],
#             [3, 7, 8 ,5 ,8],
#             [0, 1, 1, 0, 1]
#            ]

# class knn_algo:
#     def __init__(self, k):
#         self.k = k
#         self.student_marks = {}
#         self.cal_data[50] = []
        
#     def All_data(self):
        
#         self.student_marks = dict(zip(keys, values))
#         print(self.student_marks)
        
#     def formula(self, new_M, new_CS, old_M, old_CS):
#         step1 = new_M - old_M
#         step1 = step1 ** 2
#         step2 = new_CS - old_CS
#         step2 = step2 ** 2
#         last_step = step1 + step2
#         return math.sqrt(last_step)
    
#         print(self.student_marks["Math"])
#         self.student_marks["Math"]



In [20]:
# k1 = knn_algo(5)

# k1.All_data()
# k1.split_v()

{'Math': [4, 6, 7, 5, 8], 'CS': [3, 7, 8, 5, 8], 'Result': [0, 1, 1, 0, 1]}
[4, 6, 7, 5, 8]
